export const BRAND_CHOICES = [
  { name: 'Abarth', value: 'Abarth' },
  { name: 'Alfa Romeo', value: 'Alfa Romeo' },
  { name: 'Alpine', value: 'Alpine' },
  { name: 'Amuse', value: 'Amuse' },
  { name: 'Aston Martin', value: 'Aston Martin' },
  { name: 'Audi', value: 'Audi' },
  { name: 'Autobianchi', value: 'Autobianchi' },
  { name: 'BAC', value: 'BAC' },
  { name: 'BMW', value: 'BMW' },
  { name: 'Bugatti', value: 'Bugatti' },
  { name: 'Chaparral', value: 'Chaparral' },
  { name: 'Chevrolet', value: 'Chevrolet' },
  { name: 'Citroen', value: 'Citroen' },
  { name: 'Daihatsu', value: 'Daihatsu' },
  { name: 'De Tomaso', value: 'De Tomaso' },
  { name: 'Dodge', value: 'Dodge' },
  { name: 'DS Automobiles', value: 'DS Automobiles' },
  { name: 'Ferrari', value: 'Ferrari' },
  { name: 'Fiat', value: 'Fiat' },
  { name: 'Ford', value: 'Ford' },
  { name: 'Genesis', value: 'Genesis' },
  { name: 'Gillet', value: 'Gillet' },
  { name: 'Gran Turismo', value: 'Gran Turismo' },
  { name: 'Honda', value: 'Honda' },
  { name: 'Hyundai', value: 'Hyundai' },
  { name: 'Infiniti', value: 'Infiniti' },
  { name: 'Isuzu', value: 'Isuzu' },
  { name: 'Jaguar', value: 'Jaguar' },
  { name: 'Jeep', value: 'Jeep' },
  { name: 'KTM', value: 'KTM' },
  { name: 'Lamborghini', value: 'Lamborghini' },
  { name: 'Lancia', value: 'Lancia' },
  { name: 'Lexus', value: 'Lexus' },
  { name: 'Maserati', value: 'Maserati' },
  { name: 'Mazda', value: 'Mazda' },
  { name: 'McLaren', value: 'McLaren' },
  { name: 'Mercedes-AMG', value: 'Mercedes-AMG' },
  { name: 'Mercedes-Benz', value: 'Mercedes-Benz' },
  { name: 'MINI', value: 'MINI' },
  { name: 'Mitsubishi', value: 'Mitsubishi' },
  { name: 'Nissan', value: 'Nissan' },
  { name: 'Pagani', value: 'Pagani' },
  { name: 'Peugeot', value: 'Peugeot' },
  { name: 'Plymouth', value: 'Plymouth' },
  { name: 'Pontiac', value: 'Pontiac' },
  { name: 'Porsche', value: 'Porsche' },
  { name: 'Radical', value: 'Radical' },
  { name: 'RE Amemiya', value: 'RE Amemiya' },
  { name: 'Renault', value: 'Renault' },
  { name: 'RUF', value: 'RUF' },
  { name: 'Shelby', value: 'Shelby' },
  { name: 'Skoda', value: 'Skoda' },
  { name: 'SRT', value: 'SRT' },
  { name: 'Subaru', value: 'Subaru' },
  { name: 'Suzuki', value: 'Suzuki' },
  { name: 'Tesla', value: 'Tesla' },
  { name: 'Toyota', value: 'Toyota' },
  { name: 'TVR', value: 'TVR' },
  { name: 'Volkswagen', value: 'Volkswagen' },
  { name: 'Volvo', value: 'Volvo' },
  { name: 'Zagato', value: 'Zagato' },
];