// Track choices used for command autocomplete.
export const TRACK_CHOICES = [
  { name: '24H du Mans', value: '24_heures_du_mans_racing_circuit' },
  { name: 'Alsace', value: 'alsace' },
  { name: 'Lago Maggiore', value: 'autodrome_lago_maggiore' },
  { name: 'Interlagos', value: 'autodromo_de_interlagos' },
  { name: 'Monza', value: 'autodromo_nazionale_monza' },
  { name: 'Autopolis', value: 'autopolis_international_racing_course' },
  { name: 'Blue Moon Bay', value: 'blue_moon_bay_speedway' },
  { name: 'Brands Hatch', value: 'brands_hatch' },
  { name: 'Broad Bean', value: 'broad_bean_raceway' },
  { name: 'Barcelona', value: 'circuit_de_barcelona_catalunya' },
  { name: 'Sainte-Croix', value: 'circuit_de_sainte_croix' },
  { name: 'Spa', value: 'circuit_de_spa_francorchamps' },
  { name: 'Colorado Springs', value: 'colorado_springs' },
  { name: 'Daytona', value: 'daytona_international_speedway' },
  { name: 'Deep Forest', value: 'deep_forest_raceway' },
  { name: 'Dragon Trail', value: 'dragon_trail' },
  { name: 'Eiger Nordwand', value: 'eiger_nordwand' },
  { name: 'Fisherman\'s Ranch', value: 'fishermans_ranch' },
  { name: 'Fuji', value: 'fuji_international_speedway' },
  { name: 'Goodwood', value: 'goodwood_motor_circuit' },
  { name: 'Grand Valley', value: 'grand_valley' },
  { name: 'High Speed Ring', value: 'high_speed_ring' },
  { name: 'Kyoto', value: 'kyoto_driving_park' },
  { name: 'Lake Louise', value: 'lake_louise' },
  { name: 'Michelin', value: 'michelin_raceway_road_atlanta' },
  { name: 'Panorama', value: 'mount_panorama_circuit' },
  { name: 'Northern Isle', value: 'northern_isle_speedway' },
  { name: 'Nurburgring', value: 'nurburgring' },
  { name: 'Red Bull Ring', value: 'red_bull_ring' },
  { name: 'Sardegna Road', value: 'sardegna_road_track' },
  { name: 'Sardegna Wind', value: 'sardegna_windmills' },
  { name: 'Route X', value: 'special_stage_route_x' },
  { name: 'Suzuka', value: 'suzuka_circuit' },
  { name: 'Tokyo', value: 'tokyo_expressway' },
  { name: 'Trial Mountain', value: 'trial_mountain_circuit' },
  { name: 'Tsukuba', value: 'tsukuba_circuit' },
  { name: 'Watkins Glen', value: 'watkins_glen_international' },
  { name: 'Laguna Seca', value: 'weathertech_raceway_laguna_seca' },
  { name: 'Willow Springs', value: 'willow_springs_international_raceway' },
];
